[tox]
minversion = 4.0
envlist = py{39,310,311,312}, lint, docs
isolated_build = True

[testenv]
commands_pre =
  pip install maturin
  maturin develop --release
passenv =
    SSH_AUTH_SOCK
deps =
    .[dev]
commands =
  pytest {posargs}

[testenv:style]
extras =
  style
commands =
  ruff format qiskit_addon_dice_solver/
  ruff check --fix qiskit_addon_dice_solver/

[testenv:lint]
image-tester-commit = 7ae965ccf21c39e5170334ec7f4882756883860a
deps = 
  git+https://github.com/Qiskit/documentation.git@{[testenv:lint]image-tester-commit}\#egg=sphinx-alt-text-validator&subdirectory=scripts/image-tester
basepython = python3.10
extras =
  lint
commands =
  ruff format --check qiskit_addon_dice_solver/
  ruff check qiskit_addon_dice_solver/
  mypy qiskit_addon_dice_solver/
  pylint -rn qiskit_addon_dice_solver/
  reno lint

[testenv:docs]
basepython = python3.10
extras =
  docs
commands =
  sphinx-build -j auto -W -T --keep-going -b html {posargs} {toxinidir}/docs/ {toxinidir}/docs/_build/html
passenv =
  CI
  GITHUB_BASE_REF
  GITHUB_REF_NAME

[testenv:docs-clean]
skip_install = true
allowlist_externals =
  rm
commands =
  rm -rf {toxinidir}/docs/stubs/ {toxinidir}/docs/_build/
